import e from "express";

export enum CallbackStatus {
  'PENDING' = 'PENDING',
  'DONE' = 'DONE',
}

export enum SiteVisitStatus {
  EXACT_MATCH = 'EXACT_MATCH',
  NO_MATCH = 'NO_MATCH',
  COSTLY = 'COSTLY',
  PENDING = 'PENDING',
  DONE = 'DONE',
  CANCEL="CANCEL",
  CLOSURE_NEGOTIATION="CLOSURE_NEGOTIATION",
  BOOKING_DONE="BOOKING_DONE"

}

export enum LeadSharing {
  INDEPENDENT = 'INDEPENDENT',
  SHARED = 'SHARED',
}

export enum Roles {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  LEAD_MANAGER = 'LEAD_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  AGENT = 'AGENT',
  TEAM_LEAD='TEAM_LEAD',
  PRE_SALES="PRE_SALES",
  FINANCE="FINANCE"
}

export enum LeadStatus {
  NEW = 'NEW',
  INTERESTED = 'INTERESTED',
  MEETING_SITE_VISIT_SCHEDULED = 'MEETING_SITE_VISIT_SCHEDULED',
  MEETING_SITE_VISIT_DONE = 'MEETING_SITE_VISIT_DONE',
  CLOSURE_NEGOTIATION = 'CLOSURE_NEGOTIATION',
  BOOKING_DONE = 'BOOKING_DONE',
  CLIENT_BACK_OUT = 'CLIENT_BACK_OUT',
  BROKER = 'BROKER',
  ALREADY_PURCHASED = 'ALREADY_PURCHASED',
  LANGUAGE_BARRIER = 'LANGUAGE_BARRIER',
  LOW_BUDGET = 'LOW_BUDGET',
  WRONG_NUMBER = 'WRONG_NUMBER',
  NO_QUERY_POSTED = 'NO_QUERY_POSTED',
  INSTANT_NO = 'INSTANT_NO',
  REQUIRED_PROPERTY_NOT_FOUND = 'REQUIRED_PROPERTY_NOT_FOUND',
  NOT_INTERESTED = 'NOT_INTERESTED',
}

export enum LeadSubStatus {
  NEW = 'NEW',
  FOLLOW_UP = 'FOLLOW_UP',
  ASKED_TO_CALLBACK = 'ASKED_TO_CALLBACK',
  FUTURE_PROSPECT = 'FUTURE_PROSPECT',
  RINGING_NO_ANSWER = 'RINGING_NO_ANSWER',
  SWITCH_OFF = 'SWITCH_OFF',
  NOT_REACHABLE = 'NOT_REACHABLE',
  CALL_DISCONNECT = 'CALL_DISCONNECT',
  FUNDS_SHORT = 'FUNDS_SHORT',
  LOOKING_FOR_ANOTHER_OPTION = 'LOOKING_FOR_ANOTHER_OPTION',
  ALREADY_PURCHASED = 'ALREADY_PURCHASED',
  CALL_NEVER_PICKED='CALL_NEVER_PICKED'
}

export enum LeadValidity {
  VALID = 'VALID',
  INVALID = 'INVALID',
  PENDING = 'PENDING',
  FRESH = 'FRESH',
  JUNK='JUNK'
}

export enum NotificationAction{
  SITE_VISIT="SITE_VISIT",
  CALL_BACK='CALL_BACK',
  FRESH_LEADS="FRESH_LEADS",
  METTING="METTING",
  PENDING_LEADS="PENDING_LEADS",
  CUSTOM_REMINDER="CUSTOM_REMINDER"
}
export enum LeadType {
  HOT = 'HOT',
  WARM = 'WARM',
  COLD = 'COLD',
  NEW = 'NEW',
}
export enum ReminderAction{
  SITE_VISIT="SITE_VISIT",
  CALL_BACK='CALL_BACK',
  METTING="MEETING",
  FRESH_LEADS="FRESH_LEADS",
  PENDING_LEADS="PENDING_LEADS",
  CUSTOM_REMINDER="CUSTOM_REMINDER"
}

export enum LeadSources {
  FACEBOOK = 'FACEBOOK',
  GOOGLE = 'GOOGLE',
  LINKEDIN = 'LINKEDIN',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  CUSTOMER_REFERENCE = 'CUSTOMER_REFERENCE',
  INTERNAL_REFRERENCE = 'INTERNAL_REFRERENCE',
  WHATSAPP_SOCIAL = 'WHATSAPP_SOCIAL',
  WHATSAPP_SHOOTOUT = 'WHATSAPP_SHOOTOUT',
  IVR_CALL = 'IVR_CALL',
  PERSONAL_REFERENCE='PERSONAL_REFERENCE',
  OTHERS='OTHERS',
  SMS_SHOOTOUT='SMS_SHOOTOUT',
  INSTAGRAM='INSTAGRAM',
  AMOGH_WEBSITE='AMOGH_WEBSITE',
  MAGICBRICKS='MAGICBRICKS',
  HOUSING='HOUSING',
  ACRES99='ACRES99',
  SYSTEM='SYSTEM',
  IREED_WEBSITE="IREED_WEBSITE",
  SHIKSHA="SHIKSHA",
  REDMI_WEBSITE="REDMI_WEBSITE",
  HOUSE_OR_PROPERTIES="HOUSE_OR_PROPERTIES",
  SEO="SEO",
  COLD_CALLING="COLD_CALLING",
  LEAD_CHURN="LEAD_CHURN",
  YOUTUBE="YOUTUBE",
  EXISTING_CLIENT="EXISTING_CLIENT",
  CHD_EVENT="CHD_EVENT",
  WALK_IN_CLIENT="WALK_IN_CLIENT",
  BUILDER_PROVIDED_LEADS="BUILDER_PROVIDED_LEADS",
  ESTATEAVENUES="ESTATEAVENUES"

}
export enum LeafThrough{
"IVR"="IVR",
"EXCEL"="EXCEL",
"WHATSAPP"="WHATSAPP"
}
export enum Action {
  LEAD_ADDED = 'LEAD_ADDED',
}

export enum Modules {
  LEADS = 'LEADS',
  LEAD_POOL = 'LEAD_POOL',
  PERSONAL_LEAD_POOL = 'PERSONAL_LEAD_POOL',
  SITE_VISITS = 'SITE_VISITS',
}

export enum Visits {
  SITE_VISIT = 'SITE_VISIT',
  MEETING = 'MEETING',
}
export enum PermissionModule{
  LEAD_CHURN="LEAD_CHURN",
  DATA_CALLING="DATA_CALLING" ,
  REASSIGN="REASSIGN" 
}

export enum PermissionAction{
  READ="READ",
  UPDATE="UPDATE",
  CREATE="CREATE",
  DELETE="DELETE"
}
export enum LeadSourceAssign{
  GROUP="GROUP",
  INDIVIDUAL="SINGLE",
  RULES="RULES"
}
export enum TaskStatus{
  NOT_STARTED="NOT_STARTED",
  IN_PROGRESS="IN_PROGRESS",
  BLOCKED="BLOCKED",
  DONE="DONE"
}
export enum TaskPriority{
  HIGH="HIGH",
  MEDIUM="MEDIUM",
  LOW="LOW",
  URGENT="URGENT"
}

export enum Department{
  PRE_SALES="PRE_SALES",
  FINANCE="FINANCE",
  HR="HR",
  SalES="SALES",
 
}
export enum LeaveStatus{
  APPROVED="APPROVED",
  PENDING="PENDING",
  REJECTED="REJECTED"
 
}
// types/mail.types.ts
export type TemplateType = 'leave' | 'onDuty';
export type TemplateStatus = 'requestSubmitted' | 'requestApproved' | 'requestRejected';
